service: testskillfully

#package:
#  exclude:
#    - ./**
#  include:
#    - lambda/*.py

custom:
  stage: dev
  region: us-east-1
  memorySize: 128

provider:
  name: aws
  runtime: nodejs12.x
  cfnRole: arn:aws:iam::168948837935:role/masterrole
  region: ${self:custom.region}
  memorySize: ${self:custom.memorySize}

functions:
  testlambdaskill:
    handler: handler.mylamfun
    events:
      - http:
          path: myapipathgetskill
          method: GET

